#!/bin/sh

for rsrc in $@
do 
  pwd="$(pwd)"
  tmp="tmp $(date)"
  mkdir $tmp
  cd $tmp

  if [ $rsrc~="*.git" 
  then
    git clone $rsrc > /dev/null 2>&1
  elif [ $rsrc~="*.tar.gz" ]
  then
    wget $rsrc
    tar -xf *.tar.gz
    rm *.tar.gz
  else
    echo "ERROR: Unknown resource format. $rsrc"
  fi
  
  cd "$(ls)"
  if [ -f setup.py ]
  then
    sudo python setup.py install > /dev/null
  else
    echo "ERROR: Unknown package format. $rsrc"
  fi

  cd $pwd
  sudo rm -r $tmp

done
