#!/bin/bash


#extract and install resource file if exists
try_install () {
  if [ -d * ];then
    cd *
    sudo python setup.py install
  else
    echo "ERROR: Unknown package format. `ls`"    
  fi
}





for rsrc in $@
do 
  #make temporary directory
  pwd="$(pwd)"
  tmp="tmp $(date)"
  mkdir $tmp
  cd $tmp

  #download remote resource file
  if [[ $rsrc =~ \.git$ ]]; then
    git clone $rsrc > /dev/null 2>&1
    try_install
  elif [[ $rsrc =~ \.tar\.gz$ ]]; then
    wget $rsrc
    tar -xf *.tar.gz
    rm *.tar.gz
    try_install
  else
    echo "ERROR: Unknown resource format. $rsrc"
  fi

  #cleanup
  cd $pwd
  sudo rm -r $tmp
done
